class MinusLists:
    title_tester_python_web_minus_list = [
        "Разработ",
        "рекрутер",
        "писатель",
        "Наставник",
        "mentor",
        "developer",
        "us timezone",
        "Менеджер",
        "SEO",
        "Копирайтер",
        "gamedev",
        "Intern",
        "game",
        "Лингвист",
        "математик",
        "Python Teamlead",
        "Аналитик",
        "Analyst",
        "автор",
        "Programmer",
        "Сетевой",
        "студенч",
        "Тьютор",
        "Учитель",
        "роботиза",
        "Server",
        "Server",
        "Build",
        "Security",
        "конструктор",
        "Методист",
        "Специалист SAP",
        "Data engineer",
        "Педагог",
        "техлид",
        "TechLead",
        "Tech Lead продукта",
        "ментор",
        "Team Lead BI",
        "Владелец",
        "Owner",
        "Staff",
        "Java",
        ".NET",
        "Support",
        "поддержк",
        "производительности",
        "проникнов",
        "нагрузочн",
        "Стажёр",
        "Стажер",
        "Лидер",
        "Junior",
        "ручн",
        "мануал",
        "manual",
        "Performance",
        "scientist",
        "penetration",
        "trading",
        "Hospitality",
        "Coach",
        "игр",
        "Маркетолог",
        "голосовых роботов",
        "Mobile",
        "Ведущий пентестер",
        "Ruby",
        "Vue.js",
        "PHP",
        "C#",
        "C++",
        "администратор",
        "Партнер",
        "внедрен",
        "manager",
        "DevOps",
        "Recruiter",
        "Координатор",
        "Рейдер",
        "Таргетолог",
        "Преподаватель",
        "продюсер",
        "Director",
        "программист",
        "консультант",
        "системный",
        "Оператор",
        "Designer",
        "JavaScript",
        "Сорсер",
        "SRE",
        "редактор",
        "актуарий",
        "devsecops",
        "Пишущ",
        "архитектор",
        "сопровожд",
        "React",
        "Директор",
        "Руководитель",
        "дизайнер",
        "подработ",
        "consultant",
        "architect",
        "Senior Software Engineer",
    ]
    content_tester_python_web_minus_list = [
        "java",
        "php",
        "c#",
        "nitka",
    ]
    title_dev_ios_minus_list = [
    "python",
    ]