class MinusLists:
    title_tester_python_web_minus_list = [
        "Разработ",
        "рекрутер",
        "писатель",
        "Наставник",
        "developer",
        "Менеджер",
        "Копирайтер",
        "Intern",
        "Лингвист",
        "Аналитик",
        "Analyst",
        "Владелец",
        "Owner",
        "Staff",
        "Java",
        ".NET",
        "Support",
        "поддержк",
        "производительности",
        "проникнов",
        "нагрузочн",
        "Стажёр",
        "Стажер",
        "Junior",
        "ручн",
        "мануал",
        "manual",
        "Performance",
        "игр",
        "Маркетолог",
        "голосовых роботов",
        "Mobile Tech Lead",
        "Ведущий пентестер",
        "Ruby",
        "Vue.js",
        "PHP",
        "администратор",
        "внедрен",
        "manager",
        "DevOps",
        "Recruiter",
        "Координатор",
        "Рейдер",
        "Рейдер",
        "программист",
        "консультант",
        "Оператор",
        "Designer",
        "JavaScript",
        "Сорсер",
        "SRE",
        "редактор",
        "Пишущ",
        "архитектор",
        "сопровожд",
        "React",
        "Директор",
        "Руководитель",
        "дизайнер",
        "подработ",
        "Senior Software Engineer",
    ]
    title_dev_ios_minus_list = [
    "python",
    ]